export const baseUrl = '/api'
export const LIST_ACTION_TYPES={
    CHANGE_LISTS: 'CHANGE_LIST',
    ADD_LIST: 'ADD_LIST',
    REMOVE_LIST: 'REMOVE_LIST',
    CHANGE_LIST_ORDER: 'CHANGE_LIST_ORDER'
} as const

export const CARD_ACTION_TYPES={
    CHANGE_CARD: 'CHANGE_CARD',
    ADD_CARD: 'ADD_CARD',
    REMOVE_CARD: 'REMOVE_CARD',
    CHANGE_CARD_ORDER: 'CHANGE_CARD_ORDER'
} as const